Models/Client.cs
using hadsimnew.Models;

namespace hadasimExe1new.Models
{
    public class Client
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string? adress { get; set; }
        public string? city { get; set; }

        public int numAdress { get; set; }

        public System.DateTime DateOfBirth { get; set; }

        public string? Phone { get; set; }
        public string? mobilePhone { get; set; }
        //public ICollection<Vaccination>? Vaccinations { get; set; }
        public DateTime? DateOfSickness { get; set; }
        public DateTime? DateOfRecovery { get; set; }
        public string? ImageUrl { get; set; } // Variable for image



    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hadasimExe1new.Data;
using hadasimExe1new.Models;

namespace hadasimExe1new.Controllers
{
    public class ClientsController : Controller
    {
        private readonly hadasimExe1newContext _context;

        public ClientsController(hadasimExe1newContext context)
        {
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {
              return _context.Client != null ? 
                          View(await _context.Client.ToListAsync()) :
                          Problem("Entity set 'hadasimExe1newContext.Client'  is null.");
        }


        // GET: Clients/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,firstName,lastName,adress,city,numAdress,DateOfBirth,Phone,mobilePhone,DateOfSickness,DateOfRecovery,ImageUrl")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,firstName,lastName,adress,city,numAdress,DateOfBirth,Phone,mobilePhone,DateOfSickness,DateOfRecovery,ImageUrl")] Client client)
        {
            if (id != client.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Client == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var client = await _context.Client.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }

            // Find vaccines associated with the client and delete them
            var vaccines = await _context.Vaccination.Where(v => v.MemberId == id).ToListAsync();
            if (vaccines.Any())
            {
                _context.Vaccination.RemoveRange(vaccines);
            }

            _context.Client.Remove(client);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(int id)
        {
          return (_context.Client?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/VaccinationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using hadasimExe1new.Data;
using hadsimnew.Models;
using System.Reflection.PortableExecutable;
using hadasimExe1new.Models;

namespace hadasimExe1new.Controllers
{
    public class VaccinationsController : Controller
    {
        private readonly hadasimExe1newContext _context;
       
        public VaccinationsController(hadasimExe1newContext context)
        {
            _context = context;
        }

        // GET: Vaccinations
        public async Task<IActionResult> Index()
        {
            
              return _context.Vaccination != null ? 
                          View(await _context.Vaccination.ToListAsync()) :
                          Problem("Entity set 'hadasimExe1newContext.Vaccination'  is null.");
        }


        public async Task<IActionResult> Summary()
        {
            var summaryData = new Dictionary<string, object>();

            // Count customers with no vaccinations
            var unvaccinatedCustomersCount = await _context.Client
                .CountAsync(c => !_context.Vaccination.Any(v => v.MemberId == c.Id));
            summaryData["UnvaccinatedCustomersCount"] = unvaccinatedCustomersCount;

            // Calculate the start date and end date of the last month
            var startDate = DateTime.Today.AddMonths(-1).Date;
            var endDate = DateTime.Today.Date;

            // Retrieve all clients with sickness dates in the last month
            var activePatientsInLastMonth = await _context.Client
                .Where(c => c.DateOfSickness >= startDate && c.DateOfSickness <= endDate)
                .ToListAsync();

            // Group active patients by date of sickness in memory
            var activePatientsByDate = activePatientsInLastMonth
                .GroupBy(c => c.DateOfSickness.Value.Date)
                .ToDictionary(g => g.Key.ToString("yyyy-MM-dd"), g => g.Count());
            summaryData["ActivePatientsByDate"] = activePatientsByDate;

            return View(summaryData);
        }

        //Receives a client ID and returns the list of vaccinations related only to him

        public async Task<IActionResult> ViewVaccinations(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client.FirstOrDefaultAsync(m => m.Id == id);
            if (client == null)
            {
                return NotFound();
            }

            var vaccinations = await _context.Vaccination
                                                .Where(v => v.MemberId == client.Id)
                                                .ToListAsync();

            return View("Index", vaccinations);
        }


        // GET: Vaccinations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vaccination == null)
            {
                return NotFound();
            }

            var vaccination = await _context.Vaccination
                .FirstOrDefaultAsync(m => m.id == id);
            if (vaccination == null)
            {
                return NotFound();
            }

            return View(vaccination);
        }


        // GET: Vaccinations/Create
        public IActionResult Create(int memberId)
        {
            ViewData["MemberId"] = memberId;
            return View();
        }


        // POST: Vaccinations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(/*int clientId*/[Bind("id,DateVaccination,manufacturer,MemberId")] Vaccination vaccination)
        {

            if (ModelState.IsValid)
            {
                var member = _context.Client.Find(vaccination.MemberId);
                if (member == null)
                {
                    return NotFound();
                }

                var vacine = _context.Vaccination.Where(v => v.MemberId == vaccination.MemberId).ToList();
                if (vacine.Count() >= 4)
                {
                    ModelState.AddModelError("DateVaccination", "No more than four vaccines can be administered to one client");
                    return View(vaccination);
                }
                var lastVacine = vacine.OrderByDescending(v => v.DateVaccination).FirstOrDefault();
                if (lastVacine != null && lastVacine.DateVaccination > vaccination.DateVaccination)
                {
                    ModelState.AddModelError("DateVaccination", "There is no possibility of more than four vaccinations per client");
                    return View(vaccination);
                }
                _context.Add(vaccination);

                await _context.SaveChangesAsync();
                return RedirectToAction("Edit", "Clients", new { id = vaccination.MemberId });
            }
            return View(vaccination);
        }

        // GET: Vaccinations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vaccination == null)
            {
                return NotFound();
            }

            var vaccination = await _context.Vaccination.FindAsync(id);
            if (vaccination == null)
            {
                return NotFound();
            }
            return View(vaccination);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,DateVaccination,manufacturer,MemberId")] Vaccination vaccination)
        {
            if (id != vaccination.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Retrieve existing vaccinations for the same member
                var existingVaccinations = await _context.Vaccination
                                                        .Where(v => v.MemberId == vaccination.MemberId && v.id != id)
                                                        .OrderBy(v => v.DateVaccination)
                                                        .ToListAsync();

                // Check if the new date conflicts with existing dates
                foreach (var existingVaccination in existingVaccinations)
                {
                    if (vaccination.DateVaccination < existingVaccination.DateVaccination)
                    {
                        ModelState.AddModelError("DateVaccination", "The new date cannot be earlier than existing vaccination dates.");
                        return View(vaccination);
                    }
                }

                // Save changes if no conflicts found
                try
                {
                    _context.Update(vaccination);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VaccinationExists(vaccination.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }

            return View(vaccination);
        }


        // GET: Vaccinations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vaccination == null)
            {
                return NotFound();
            }

            var vaccination = await _context.Vaccination
                .FirstOrDefaultAsync(m => m.id == id);
            if (vaccination == null)
            {
                return NotFound();
            }

            return View(vaccination);
        }

        // POST: Vaccinations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Vaccination == null)
            {
                return Problem("Entity set 'hadasimExe1newContext.Vaccination'  is null.");
            }
            var vaccination = await _context.Vaccination.FindAsync(id);
            if (vaccination != null)
            {
                _context.Vaccination.Remove(vaccination);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VaccinationExists(int id)
        {
          return (_context.Vaccination?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Views/Clients/Create.cshtml
@model hadasimExe1new.Models.Client

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="adress" class="control-label"></label>
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="city" class="control-label"></label>
                <input asp-for="city" class="form-control" />
                <span asp-validation-for="city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numAdress" class="control-label"></label>
                <input asp-for="numAdress" class="form-control" />
                <span asp-validation-for="numAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobilePhone" class="control-label"></label>
                <input asp-for="mobilePhone" class="form-control" />
                <span asp-validation-for="mobilePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfSickness" class="control-label"></label>
                <input asp-for="DateOfSickness" class="form-control" />
                <span asp-validation-for="DateOfSickness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRecovery" class="control-label"></label>
                <input asp-for="DateOfRecovery" class="form-control" />
                <span asp-validation-for="DateOfRecovery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Delete.cshtml
@model hadasimExe1new.Models.Client

@{
    ViewData["Title"] = "Delete";
}
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.city)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numAdress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numAdress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mobilePhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mobilePhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfSickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfSickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRecovery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfRecovery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Clients/Details.cshtml
@model hadasimExe1new.Models.Client

@{
    ViewData["Title"] = "Details";
}
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}
<h1>Details</h1>

<div>
    <h4>Client</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.firstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.firstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.lastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.lastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.city)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.city)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numAdress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numAdress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.mobilePhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.mobilePhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfSickness)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfSickness)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfRecovery)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfRecovery)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)

        </dd>
      
    </dl>
</div>
<!-- Button to view vaccinations -->
<div>
    <form asp-action="ViewVaccinations" asp-controller="Vaccinations" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-danger">View Vaccinations</button>
    </form>
</div>

<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" style="color: red;">Edit</a> |
    <a asp-action="Index" style="color: red;">Back to List</a>
</div>

Views/Clients/Edit.cshtml
@model hadasimExe1new.Models.Client

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Client</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="firstName" class="control-label"></label>
                <input asp-for="firstName" class="form-control" />
                <span asp-validation-for="firstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="lastName" class="control-label"></label>
                <input asp-for="lastName" class="form-control" />
                <span asp-validation-for="lastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="adress" class="control-label"></label>
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="city" class="control-label"></label>
                <input asp-for="city" class="form-control" />
                <span asp-validation-for="city" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="numAdress" class="control-label"></label>
                <input asp-for="numAdress" class="form-control" />
                <span asp-validation-for="numAdress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="mobilePhone" class="control-label"></label>
                <input asp-for="mobilePhone" class="form-control" />
                <span asp-validation-for="mobilePhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfSickness" class="control-label"></label>
                <input asp-for="DateOfSickness" class="form-control" />
                <span asp-validation-for="DateOfSickness" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfRecovery" class="control-label"></label>
                <input asp-for="DateOfRecovery" class="form-control" />
                <span asp-validation-for="DateOfRecovery" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control" />
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div>
                <a href="@Url.Action("Create", "Vaccinations", new { memberId = Model.Id })" class="btn btn-danger">Add Vaccine</a>
            </div>


            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-danger" />
            </div>

        </form>
    </div>
</div>
<!-- Button to view vaccinations -->
<div>
    <form asp-action="ViewVaccinations" asp-controller="Vaccinations" asp-route-id="@Model.Id" method="get">
        <button type="submit" class="btn btn-danger">View Vaccinations</button>
    </form>
</div>
<div>
    <a asp-action="Index" style="color: red;">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Clients/Index.cshtml
@model IEnumerable<hadasimExe1new.Models.Client>

@{
    ViewData["Title"] = "Client";
}
@{
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<div class="ml-55">
    <p style="font-size: larger;">
        <a asp-action="Create" style="color: red;">Click here to create a new Client</a>
    </p>
</div>

<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-12">
            </div>
        </div>
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-lg-3 col-md-6 mb-4 pb-2">
                    <div class="product-item d-flex flex-column align-items-center text-center bg-light rounded py-5 px-3">

                        <div class="position-relative rounded-circle mt-n3 mb-4 p-3 bg-secondary" style="width: 150px; height: 150px;">
                            <img class="rounded-circle w-100 h-100" src="@item.ImageUrl" style="object-fit: cover;">
                        </div>
                        <h5 class="font-weight-bold mb-4">@item.firstName</h5>
                        <h5 class="font-weight-bold mb-4">@item.lastName</h5>

                        <div>
                            <a asp-action="Edit" asp-route-id="@item.Id" style="color: red;">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.Id" style="color: red;">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.Id" style="color: red;">Delete</a>
                        </div>

                    </div>
                </div>
            }
        </div>
    </div>
</div>